
name: Sync Multiple Image

on:
  workflow_dispatch: 


env:
  ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
  ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
  NAMESPACE: ${{ secrets.NAMESPACE }}

jobs:
  sync-multiple-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 安装 image-syncer
      - name: install image-syncer Tool
        run: |
          target_tag=$(curl --silent "https://api.github.com/repos/AliyunContainerService/image-syncer/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
        
          wget https://github.com/AliyunContainerService/image-syncer/releases/download/$target_tag/image-syncer-$target_tag-linux-amd64.tar.gz
          
          tar -xvf image-syncer-"${target_tag}"-linux-amd64.tar.gz

      - name: add sercret to file
        run: |
          envsubst < auth.json > multiple-auth.json
          envsubst < images.json > multiple-images.json
          
      - name: sync image
        run: ./image-syncer --proc=6 --auth=./multiple-auth.json --images=./multiple-images.json --retries=3
