
name: Sync Single Image

on:
  workflow_dispatch: 
    inputs:
      source:
        description: '镜像源 (Registry)'     
        required: true
        default: 'docker.io'
      source-image: 
        description: '源镜像 (Image)'     
        required: true
        default: ''
      destination:
        description: '目标源 (Registry)'
        required: true
        default: 'registry.cn-hangzhou.aliyuncs.com'
      destination-image:
        description: '目标镜像 (Image)'
        required: true
        default: ''


env:
  ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
  ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
  SOURCE: ${{ inputs.source }}
  SOURCE-IMAGE: ${{ inputs.source-image }}
  DESTINATION: ${{ inputs.destination }}
  DESTINATION-IMAGE: ${{ inputs.destination-image }}


jobs:
  sync-single-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 安装 image-syncer
      - name: install image-syncer Tool
        run: |
          target_tag=$(curl --silent "https://api.github.com/repos/AliyunContainerService/image-syncer/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
        
          wget https://github.com/AliyunContainerService/image-syncer/releases/download/$target_tag/image-syncer-$target_tag-linux-amd64.tar.gz
          
          tar -xvf image-syncer-"${target_tag}"-linux-amd64.tar.gz

      - name: add sercret to file
        run: |
          envsubst < auth.json > single-auth.json
          envsubst < image.json > single-image.json

      - name: sync image
        run: ./image-syncer --proc=6 --auth=./single-auth --images=./single-image.json --retries=3
